#!/usr/bin/with-contenv bash

# If needed add dafault config
if [[ ! -f /config/config.ini ]]; then
    cp /defaults/config.ini /config/config.ini
fi

# permissions
chown -R abc:abc \
    /app \
    /config
